
spring.datasource.url=jdbc:postgresql://localhost:5432/vaultpay
spring.datasource.username=postgres
spring.datasource.password=6005073256

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true